### PR TITLE
No padding for build panel

### PR DESCRIPTION
**Pull request by noseglid**
Like any UI change this is debatable. I really don't like the padding on the build panel. I've had this in my `styles.less` for a while, and thought I'd make a PR out of it. I'm sure more feel the same as I do.

Thanks for a great theme. My first choice, btw!

### CODE REVIEW

**Comment by noseglid** [comment]
Also, there's been quite some changes to the `build` panel since you made these changes. Perhaps you'd like to go over it one more time with your keen eye for color and layout :)

**Comment by ignism** [comment]
Heyo, sorry for the super late reply. 
I checked the build panel and it seems fine for me, the way it is right now. I tried to add the line you suggested but it didn't seem to do anything. Did it fix itself?

**Comment by noseglid** [comment]
Nope, seem to still be an issue.
With padding:
screen shot 2016-04-22 at 15 36 03

Without padding:
screen shot 2016-04-22 at 15 36 12

**Comment by ignism** [comment]
Ah I see, you actually want it like that. But then the text is touching the lines... brrrrr.
Also, I love your package. Let me try to find something that works for the both of us.

**Comment by noseglid** [comment]
Maybe it can be reduced a bit rather than set to 0 ?

I love your UI, it's the one I use all day everyday :)

**Comment by ignism** [comment]
I noticed that the bottom panels are not aligned well. For instance if I open up the find/replace along with the build panel and terminal-plus panel for intance. Buttons don't align nicely. It's actually the find/replace panel that has different positioning from the other two, so I might want to fiddle in there.
As for the padding, I want to suggest to remove the padding for the "console". But then it needs to have some padding inside the console I think.

**Comment by ignism** [comment]
I removed all padding for now.

**Comment by noseglid** [comment]
Adding padding inside the terminal itself isn't trivial since the number of characters in width/height that is sent to the underlaying command/pseudo-terminal is calculated from that width and heigh. It would certainly be doable, but might require changes in `atom-build`.

**Comment by ignism** [comment]
I added the padding left and right in nuclues itself now, see for yourself how you like it. it just gives the text inside te terminal a little bit more space.

**Comment by noseglid** [comment]
It completely destroyed the calculations 😞 
screen shot 2016-04-25 at 14 36 28

After removing the [recently added left- and right padding](https://github.com/ignism/nucleus-dark-ui/commit/361dc1c9ef8e61a5f4c471455fd4f0012502c17f#diff-62485a5fa27484032b106bbe3de4b5e5R75). It works (but very close to the line):
screen shot 2016-04-25 at 14 36 59

**Comment by ignism** [comment]
will patch this right away

**Comment by ignism** [comment]
Do you have an example command, so I can reproduce the error above?

**Comment by noseglid** [comment]
Something like this would work:

`.atom-build.yml`:

```
cmd: echo this is a very long line which may be line wrapped by the terminal component
```

Then resize the window so it doesn't fit on one line.

**Comment by ignism** [comment]
screen shot 2016-04-25 at 14 52 40
screen shot 2016-04-25 at 14 52 24

I removed the padding from .terminal and moved it one level higher to .output, seems to be working for me.

**Comment by noseglid** [comment]
Yes that looks really nice! Thanks for the super fast turnaround!

**Comment by ignism** [comment]
whoopsie... I removed all styles in `packages.less` except for yours, grab 0.7.20 to fix this :)

**Pull request closed without merging**
