### PR TITLE
use relative font-size

### PR DESCRIPTION
**Pull request by zhaocai**
> Can you use relative font-size? #69

### CODE REVIEW

**Comment by ignism** [comment]
This is really great work! As I said I was going to implement it in de the next patch, the reason it wasn't in the small patch is because I am working on a total overhaul. The theme has been updated and hacked so much that everytime I fixed something, something else stopped working (I threw `!important`s everywhere for instance) So, meanwhile I have been working on the theme starting from scratch. It will be awesome and I will finally release it as 1.0.0, I am going to take these changes you made. And put them in my new repo too! After testing, I will put every change made back into this repo.

**Comment by zhaocai** [comment]
delight to know that you are working on overhauling this already awesome theme 👍

**Comment by zhaocai** [comment]
Thanks for the update :thumbsup:

Regarding version 0.10.1, I have two issues:
1. The `font-size` is still px-based in `ui-variables.less`
   
   ``` cson
   @font-size: 13px;
   @input-font-size: 13px;
   
   @disclosure-arrow-size: 12px;
   
   @component-padding: 10px;
   @component-icon-padding: 5px;
   @component-icon-size: 16px;
   @component-line-height: 2rem;
   @component-border-radius: 4px;
   ```
2. I really like the old style for `command-palette`. How can I get it back?

**Comment by ignism** [comment]
All the font sizes are now relative to the @font-size variable. changing that variable doesn't make sense.

I changed the overlay to a contrasting color because they call for immediate action. I liked it how the overlay form Linter looks like and I adapted everything to look just like it.

That said, you can change it to any coloring in your own Atom stylesheet.

**Pull request merged**
